website/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('interviewers.url')),
    path('', include('accounts.url')),
    path('', include('streamapp.url')),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls'))

]

interviewers/models.py
from datetime import timedelta, date

from django.contrib.auth.models import User
from django.db import models
from django.utils.datetime_safe import datetime
# Create your models here.

class Job(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    created_by = models.ForeignKey(User,related_name='createdBy',default="", on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name


class Questions(models.Model):
    question = models.CharField(max_length=100)
    answer = models.CharField(max_length=100, default=None)
    questDur = models.CharField(max_length=100, default=None)
    skills = models.CharField(max_length=200,default=" ")
    description = models.CharField(max_length=300,default="")
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.question


class Interviews(models.Model):
    title = models.CharField(max_length=300,default="")
    job = models.ForeignKey(Job,related_name='interviews',on_delete=models.CASCADE)
    description = models.CharField(max_length=300,default="")
    created_by = models.ForeignKey(User,related_name='User',default="",on_delete=models.CASCADE)
    Expiration_date= models.DateTimeField(default=date.today()+timedelta(3))
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.now, blank=True)

class InterviewQuestions(models.Model):
    order = models.IntegerField(default=0)
    interview = models.ForeignKey(Interviews, on_delete=models.CASCADE)
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    class Meta:
        ordering = ['order']

    def __str__(self):
        # template = '{0.order} {0.question.id} {0.question.answer} {0.question.questDur} {0.interview}'
        # return template.format(self)
        return self.question.id


class Companies(models.Model):
    name = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    phoneNo = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Interviewees(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True, default="")
    send_by = models.ForeignKey(User,related_name="interviewee_send_by",on_delete=models.CASCADE)
    state = models.CharField(max_length=100, default="Waiting")
    def __str__(self):
        return self.name
class Applicants(models.Model):
    interview = models.ForeignKey(Interviews, related_name='applicant', on_delete=models.CASCADE)
    interviewee = models.ForeignKey(Interviewees, related_name='applicant', on_delete=models.CASCADE)
    invitationLink = models.CharField(max_length=300,default="")

    def __str__(self):
        return self.state

    def get_state(self):
        ret = ''
        print(self.applicants.all())
        # use models.ManyToMany field's all() method to return all the Department objects that this employee belongs to.
        for app in self.applicant.all():
            ret = ret + app.state + ','
        # remove the last ',' and return the value.
        return ret[:-1]

class Report(models.Model):
    applicant= models.ForeignKey(Applicants,related_name="report",on_delete=models.CASCADE)
    report = models.FileField(upload_to='videos/', null=True, verbose_name="")

class CompanyUsers(models.Model):
    company = models.ForeignKey(Companies,related_name='companyUsers', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='companyUsers', on_delete=models.CASCADE)

class ApplicantQues(models.Model):
    applicant= models.ForeignKey(Applicants,related_name="appQues",on_delete=models.CASCADE)
    question = models.ForeignKey(Questions,related_name="appQues",on_delete=models.CASCADE)
    videoAns = models.FileField(upload_to='videos/', null=True, verbose_name="")

    class Meta:
        verbose_name = 'video'
        verbose_name_plural = 'videos'

templates/interview/addInterview.html
{% extends "master.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} New Interview {% endblock %}
{% block stylesheet %}
    <style>
    .con{
        box-shadow: 0px 0px 5px 5px #cce5ff;
        padding: 10px
    }
    .interview-form{
        margin-top: 8%;
        margin-left: 15%;
    }
    #question{
        border: 2px solid gray;
        box-shadow: 5px 5px 5px darkslategrey;
        margin-bottom: 10px;
        padding: 10px;
    }
    #question input{
        box-shadow: none;
    }
    .interview-form{
         width: 60%;
    }
    </style>
    <link rel="stylesheet" href="{% static 'css/addInterview1.css' %}">
{% endblock %}

    {% block content %}
{#        {%  include "navbar.html" %}#}
{% include "sidebar.html" %}
        <br>
                <div class="container mt-5 w-50 interview-form">
        <form role="form" class="needs-validation" id="interview" method="post" novalidate class="mb-4">
        {% csrf_token %}
           {{ interview|crispy }}

            <button class=" m-2 btn" type="submit">Save </button>


        </form>
</div>

    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    {% endblock javascript %}

    {% endblock %}
    </ol>

templates/interview/addinterviewQues.html
{% extends "master.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Add Quetions {% endblock %}
{% block stylesheet %}
    <style>
    .con{
        box-shadow: 0px 0px 5px 5px #cce5ff;
        padding: 10px
    }
    .interview{
        margin-top: 8%;
        margin-left: 10%;
    }
    #question{
        border: 2px solid gray;
        box-shadow: 5px 5px 5px darkslategrey;
        margin-bottom: 10px;
        padding: 10px;
    }
    #question input{
        box-shadow: none;
    }

    .container p{
        font-size: 20px;
    }
    </style>
    <link rel="stylesheet" href="{% static 'css/addInterview1.css' %}">
{% endblock %}

    {% block content %}
{#        {%  include "navbar.html" %}#}
{% include "sidebar.html" %}
        <br>
                <div class="container interview mt-8 w-75 ">
                    <p><span style="font-size: 30px;font-weight: bold"> Job Title : </span>{{ interview.job.name }}</p>
                    <p><span style="font-size: 30px;font-weight: bold"> Interview Title : </span>{{ interview.title }}</p>
                   <hr>
                                    {% if questions != 0 %}

                    <h3 for="">Questions</h3>
                    <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Order</th>
      <th scope="col">Question</th>
      <th scope="col">Answer</th>
      <th scope="col">Duration</th>
      <th scope="col">Skills</th>
      <th scope="col">Notes</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
  {% for question in questions %}
    <tr>
      <th scope="row">{{ forloop.counter }} </th>
      <td>{{ question.question }}</td>
      <td>{{ question.answer }}</td>
      <td>{{ question.questDur }} mins</td>
      <td>{{ question.skills }} mins</td>
      <td>{{ question.description }} mins</td>
      <td>
          <a href="{% url "delete_question" interview.id question.id %}"><img width="20" height="20" src="{% static "img/remove.svg" %}"></a></td>

    </tr>
    {% endfor %}
  </tbody>
</table>
                    {% endif %}
        <form role="form" class="needs-validation" id="question" method="post" novalidate class="mb-4" >
        {% csrf_token %}
            <input type="hidden" name="interview_id" value="{{ interview.id }}">
        {{ questForm|crispy }}

        <div id="result">

        </div>

            <button class=" m-2 btn" type="submit">Save Changes </button>

        </form>
{#        <button class=" m-2 btn" id="addQuest">Add Question </button>#}

</div>

    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script>
        $(document).ready(function () {
            // catch the form's submit event
            $('#addQuest').click(function () {
                $('#question').css('display', 'block');
                $('#addQuest').css('display', 'none');


                // create an AJAX call
                {#$.ajax({#}
                {#    data: $(this).serialize(), // get the form data#}
                {#    url: "{% url 'add_question' %}",#}
                {#    // on success#}
                {#    success: function (response) {#}
                {#        console.log(response);#}
                {#        $('#question').css('display', 'inline-block');#}
                {#        $('#result').append(response);#}
                {##}
                {#    },#}
                {##}
                {#    // on error#}
                {#    error: function (response) {#}
                {#        // alert the error if any error occured#}
                {#        console.log(response.responseJSON.errors)#}
                {#    }#}
                {#                });#}
                {#return false;#}
            });
        })


    </script>
    {% endblock javascript %}

    {% endblock %}
    </ol>
{#{% for question in questions %}#}
{#                <div id="question">#}
{#               {{ question|crispy }}#}
{#            <div id="question">#}
{#                <div class="form-group">#}
{#                    <label for="question">Question*</label>#}
{#                    <input type="text" class="form-control" id="question" name="question" placeholder="Write the question" maxlength="200" required="true">#}
{#                </div>#}
{#                <div class="form-group">#}
{#                    <label for="question">Answer*</label>#}
{#                    <input type="text" class="form-control" id="answer" name="answer" placeholder="Write the answer" maxlength="200">#}
{#                </div>#}
{#               <div class="form-group">#}
{#                   <label for="questDur">Question Duration: </label>#}
{#                   <select  class="form-control" id="questDur" name="questDur" required="true">#}
{#                       <option selected disabled>Question Duration</option>#}
{#                       <option value="1">1   min</option>#}
{#                       <option value="2">2   mins</option>#}
{#                       <option value="5">5   mins</option>#}
{#                       <option value="10">10 mins</option>#}
{#                       <option value="15">15 mins</option>#}
{#                   </select>#}
{#               </div>#}
{#            </div>#}
{#            {% endfor %}#}

templates/interview/interview.html
{% extends "master.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{ interview.title  }} {% endblock %}
{% block stylesheet %}
    <style>
    body{
        background-color: #f5f5f5;
        margin-left: 15%;
    }
    .interview{
        margin-top: 6%;
    }

    #question input{
        box-shadow: none;
    }

    .container p{
        font-size: 20px;
    }
      .navbar{
          background-color: white;
          height: 5px;
    }
    .navbar ul li a{
        color: black;
        font-size: 18px;
        font-weight: bold;
    }
    .col{
        padding:5px ;
        margin: 5px;
        width: 15rem;
        background-color: white;
        height: 6rem;
    }
    </style>
    <link rel="stylesheet" href="{% static 'css/addInterview1.css' %}">
{% endblock %}

    {% block content %}
{% include "sidebar.html" %}
        <br>

        <div class="container interview">
            <p style="font-size: 30px;font-weight: bold">{{ interview.title }}</p>
            <div class="row">
                <div class="col d-sm-flex" >
                    <div class=" p-2"style="background-color: #33cccc;border-radius: 5px;">
                        <img src="{% static "img/group.png" %}" style="width: 3rem;height: 4rem"/>
                    </div>
                    <div class="p-2 justify-content-center">
                        <p>All Invitations</p>
                        <p>5</p>
                    </div>
                </div>
                <div class="col d-sm-flex" >
                    <div class=" p-2" style="background-color:#cc0000;border-radius: 5px;">
                        <img src="{% static "img/waiting.png" %}" style="width: 3rem;height: 4rem"/>
                    </div>
                    <div class="p-2 justify-content-center">
                        <p>Waiting</p>
                        <p>5</p>
                    </div>
                </div>
                <div class="col d-sm-flex" >
                    <div class=" p-2"  style="background-color:#ffff33;border-radius: 5px;">
                        <img src="{% static "img/progress.png" %}" style="width: 3rem;height: 4rem"/>
                    </div>
                    <div class="p-2 justify-content-center">
                        <p>In Progress</p>
                        <p>5</p>
                    </div>
                </div>
                <div class="col d-sm-flex" >
                    <div class=" p-2" style="background-color:#2eb82e;border-radius: 5px;">
                        <img src="{% static "img/interviewed.png" %}" style="width: 3rem;height: 4rem"/>
                    </div>
                    <div class="p-2 justify-content-center">
                        <p>Interviewed</p>
                        <p>5</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="container row">
        <div class="d-block col col-md-3" style="background-color: white;margin-top: 20px;height: 100%">
                <button class="btn btn-primary"style="background-color: blue;color: white;width: 100%" type="button" data-toggle="collapse" data-target="#description" aria-expanded="false" aria-controls="description">
                    {{ interview.title}}
                </button>
                <div class="collapse py-2" id="description">
                    <div class=" my-2">
                        <h4>Description</h4>
                        <p>{{ interview.description }}</p>
                        <h4>Employee Skills</h4>

{#                        array of questions skills and include them in string#}
                    <ul>
                        {% for q in questions %}
                            {% for skill in q.skills %}
                            <li class="bold" style="font-size: 20px"> {{  skill}}</li>
                                  {% endfor %}
                                  {% endfor %}
                    </ul>
                        </div>
                </div>
            </div>

        <div class="d-block col col-md-8 mx-2" style="background-color: white;margin-top: 20px;height: 100%">
           <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
               <li class="nav-item" role="presentation">
                   <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-questions" role="tab" aria-controls="pills-questions" aria-selected="true">Questions List</a>
               </li>
               <li class="nav-item" role="presentation">
                   <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-sendInvitation" role="tab" aria-controls="pills-sendInvitation" aria-selected="false">Send Invitation</a>
               </li>
               <li class="nav-item" role="presentation">
                   <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-invitations" role="tab" aria-controls="pills-invitation" aria-selected="false">Invitation List</a>
               </li>
           </ul>
            <div class="tab-content" id="pills-tabContent">
{#                tab questions#}
                <div class="tab-pane fade show active" id="pills-questions" role="tabpanel" aria-labelledby="pills-questions-tab">
                    <div class="container">
                        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
                            <div class="row"><div class="col-sm-12 col-md-4">
                                <div class="dataTables_length" id="dataTable_length">
                                    <label>Show <select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div>
                                <div class="col-sm-12 col-md-4"><div id="dataTable_filter" class="dataTables_filter"><label>Search:<input type="search" class="form-control form-control-sm" placeholder="" aria-controls="dataTable"></label></div></div>
                                <div class="col-sm-12 col-md-4"><a href="{% url "addInterQues" interview.id %}" class="btn btn-primary">Add Question</a></div>

                            </div>
                            <div class="row"><div class="col-sm-12">
                                <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>
                            <tr role="row">
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending"style="width: 35%;">Question</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending"style="width: 5%">Question Duration</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 25%;">Skill(s)</th>
                                <th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" ></th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for question in questions %}
                            <tr role="row" class="odd">
                               <td class="sorting_1">{{ question.question }}</td>
                               <td>{{ question.questDur }}</td>
                              <td>
                                  {% for skill in question.skills %}
                                      <span class="text-white"
                                            style="background-color:#14a635;margin-left:2px;font-weight:bold;border-radius: 5px;padding: 2px">{{  skill}}</span>
                                  {% endfor %}
                              </td>
                               <td><div>
                                   <a class="btn btn-primary">Edit</a>
                                   <a href="{% url "delete_question" interview.id question.id%}" class="btn btn-danger">Delete</a>
                               </div></td>
                             </tr>
                            {% endfor %}
                         </tbody>
                        </table>
                        </div>
                            </div>
                        </div></div></div>
                <div style="padding: 5px" class="tab-pane fade" id="pills-sendInvitation" role="tabpanel" aria-labelledby="pills-sendInvitation-tab">
                    <form method="post" novalidate class="mb-4">
                        {% csrf_token %}
                        {{ intervieweeForm|crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <div class="tab-pane fade" id="pills-invitations" role="tabpanel" aria-labelledby="pills-invitations-tab">
 <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                            <thead>
                            <tr role="row">
                                <th></th>
                                <th style="width: 20%;">Name</th>
                                <th>Email</th>
                                <th style="width: 10%;">State</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for interviewee in interviewees %}
                            <tr role="row" class="odd">
                               <td class=""> {{ forloop.counter }}</td>
                               <td class="">{{ interviewee.name }}</td>
                               <td>{{ interviewee.email }}</td>
                              <td>{{ interviewee.state }}</td>
                               <td><div>
                                   <a class="btn btn-primary">Edit</a>
                                   <a class="btn btn-danger">Delete</a>
                                   <a href="{% url "report" interviewee.id %}" class="btn btn-info">View Report</a>
                               </div></td>
                             </tr>
                            {% endfor %}
                         </tbody>
                        </table>
                </div>
            </div>
        </div>
        </div>




    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    {% endblock %}
{% endblock %}
    </ol>

templates/interview/interviews.html
{% extends "master.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheet %}
    <style>
   .container{
       margin-top: 10%;
       margin-left: 20%;
   }
    .table{
        width: 80%;
    }
    </style>
{% endblock %}
{% block title %} Interviews {% endblock %}

    {% block content %}
{% include "sidebar.html" %}
        <div class="container">
                   <a class="btn btn-info justify-content-end"
                   href="{% url "add_interview" %}">Add New Interview</a></div>
        <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Job Title</th>
      <th scope="col">Name</th>
      <th scope="col">Questions</th>
      <th scope="col">Created By</th>
      <th scope="col">Delete</th>

    </tr>
  </thead>
  <tbody>
  {% for interview in interviews %}
    <tr>
      <th scope="row">{{ forloop.counter }} </th>
      <td>{{ interview.job.name }}</td>
      <td><a href="{% url "interview" interview.id  %}" style="color: black">{{ interview.title }}</a></td>
      <td>{{ interview.interviewquestions_set.count }}</td>
      <td>{{ interview.created_by }}</td>
      <td>
          <a href="{% url "delete_interview" interview.id %}"><img width="20" height="20" src="{% static "img/remove.svg" %}"></a></td>

    </tr>
    {% endfor %}
  </tbody>
</table>

        </div>
{% endblock %}